# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: "2"

services:
  nestjs-kafka: 
    image: "nestjs-kafka"
    container_name: "nestjs-kafka"
    build:
      context: .
      dockerfile: ./apps/nestjs-kafka/Dockerfile
    command: ["pnpm", "start:prod:nestjs-kafka"]
    ports:
      - "3000:3000"
    depends_on:
      - producer

  producer: 
    image: "producer"
    container_name: "producer"
    build:
      context: .
      dockerfile: ./apps/producer/Dockerfile
    command: ["pnpm", "start:prod:producer"]
    depends_on:
      - kafka

  consumer: 
    image: "consumer"
    container_name: "consumer"
    build:
      context: .
      dockerfile: ./apps/consumer/Dockerfile
    command: ["pnpm", "start:prod:consumer"]
    depends_on:
      - kafka

  kafka:
    image: docker.io/bitnami/kafka:3.6
    container_name: "kafka"
    ports:
      - '9094:9094'
    volumes:
      - "kafka_data:/bitnami"
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
volumes:
  kafka_data:
    driver: local
